spring:
  pulsar:
    client:
      service-url: pulsar://localhost:6650
    admin:
      service-url: http://localhost:8080
    producer:
      topic-name: my-topic-1
      message-type: java.lang.String
    consumer:
      subscription-name: my-subscription
      topics: my-topic-1
      subscription-type: Exclusive
      message-type: java.lang.String